# Deployment is responsible for keeping a set of pods running
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: scheduler
  name: scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduler
  strategy: {}
  template:
    metadata:
      labels:
        app.network/default: "true"
        app: scheduler
    spec:
      containers:
        - image: tkrishtop/scheduler:scheduler
          name: scheduler
          # to always pull the latest image
          imagePullPolicy: Always
          ports:
            - containerPort: 5555
          resources: {}
      restartPolicy: Always
status: {}
